### PR TITLE
Added lbry credits updated icon

### PR DESCRIPTION
**Pull request by iamflorencejay**

### CODE REVIEW

**Comment by PavlosTze** [comment]
Please see the guidelines in the readme. Also, an announcement or proof that LBRY has changed to this icon.

**Comment by LaroTayoGaming** [comment]
@PavlosTze https://lbry.tv/@lbry:3f/lbryeconomy2020:5

**Comment by LaroTayoGaming** [comment]
this is the announcement @PavlosTze

**Comment by mahdiamer** [comment]
> _No description provided._

**Review by mahdiamer — APPROVED** [review]

**Comment by iamflorencejay** [comment]
@PavlosTze any update about this?

**Comment by iamflorencejay** [comment]
any updates?

**Comment by coinomiAngelos** [comment]
Merged. Please note that further actions are needed for the icon to appear in the apps, which will be in the next releases on all platforms. Thanks!

**Pull request merged**
